export const storeProducts = [
  {
    id: 1,
    title: "Rome Planter mini",
    img: "img/product-1.png",
    price: 4,
    size: "Diameter 2 inches",
    color: "brown",
    material: "",
    info: "Lorem ipsum dolor sit amet, mei iudico equidem an, duis decore persius sea ne. Duo nominati reformidans at. Ei mel soleat cetero, ei libris vivendo duo, cum laboramus intellegat ex. Id vim legimus consequat.",
    author: "Nik",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 2,
    title: "Rome Planter small",
    img: "img/product-2.png",
    price: 6,
    size: "Diameter 3 inches",
    color: "brown",
    material: "",
    info: "Lorem ipsum dolor sit amet, mei iudico equidem an, duis decore persius sea ne. Duo nominati reformidans at. Ei mel soleat cetero, ei libris vivendo duo, cum laboramus intellegat ex. Id vim legimus consequat.",
    author: "Nik",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 3,
    title: "Rome Planter medium",
    img: "img/product-3.png",
    price: 8,
    size: "Diameter 4 inches",
    color: "brown",
    material: "",
    info: "Lorem ipsum dolor sit amet, mei iudico equidem an, duis decore persius sea ne. Duo nominati reformidans at. Ei mel soleat cetero, ei libris vivendo duo, cum laboramus intellegat ex. Id vim legimus consequat.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 4,
    title: "Rome Planter large",
    img: "img/product-4.png",
    price: 12,
    size: "Diameter 7 inches",
    color: "brown",
    material: "",
    info: "Lorem ipsum dolor sit amet, mei iudico equidem an, duis decore persius sea ne. Duo nominati reformidans at. Ei mel soleat cetero, ei libris vivendo duo, cum laboramus intellegat ex. Id vim legimus consequat.",
    author: "Nik",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "Planter",
    img: "img/product-5.png",
    price: 5,
    size: "Diameter 3 inches",
    color: "black",
    material: "",
    info: "Lorem ipsum dolor sit amet, mei iudico equidem an, duis decore persius sea ne. Duo nominati reformidans at. Ei mel soleat cetero, ei libris vivendo duo, cum laboramus intellegat ex. Id vim legimus consequat.",
    author: "Nik",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 6,
    title: "Table Clock",
    img: "img/product-6.png",
    price: 40,
    size: "",
    color: "brown",
    material: "wood",
    info: "Lorem ipsum dolor sit amet, mei iudico equidem an, duis decore persius sea ne. Duo nominati reformidans at. Ei mel soleat cetero, ei libris vivendo duo, cum laboramus intellegat ex. Id vim legimus consequat.",
    author: "Nik",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 7,
    title: "Paper Organizer",
    img: "img/product-7.png",
    price: 120,
    size: "",
    color: "light brown",
    material: "Reclaimed 100 yr old Douglas Fir, Oak dowels, acrylic tray, danish oil with walnut finish",
    info: "Lorem ipsum dolor sit amet, mei iudico equidem an, duis decore persius sea ne. Duo nominati reformidans at. Ei mel soleat cetero, ei libris vivendo duo, cum laboramus intellegat ex. Id vim legimus consequat.",
    author: "Nik",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 8,
    title: "Winter Scarf",
    img: "img/product-8.png",
    price: 80,
    size: "",
    color: "dark blue",
    material: "",
    info: "Lorem ipsum dolor sit amet, mei iudico equidem an, duis decore persius sea ne. Duo nominati reformidans at. Ei mel soleat cetero, ei libris vivendo duo, cum laboramus intellegat ex. Id vim legimus consequat.",
    author: "Zinfira",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 9,
    title: "Blanket",
    img: "img/product-9.png",
    price: 150,
    size: "",
    color: "grey-pink",
    material: "",
    info: "Lorem ipsum dolor sit amet, mei iudico equidem an, duis decore persius sea ne. Duo nominati reformidans at. Ei mel soleat cetero, ei libris vivendo duo, cum laboramus intellegat ex. Id vim legimus consequat.",
    author: "Zinfira",
    inCart: false,
    count: 0,
    total: 0
  }
];

export const detailProduct = {
  id: 1,
  title: "Rome Planter",
  img: "img/product-9.png",
  price: 4,
  size: "Diameter 2 inches",
  color: "brown",
  material: "",
  info: "Lorem ipsum dolor sit amet, mei iudico equidem an, duis decore persius sea ne. Duo nominati reformidans at. Ei mel soleat cetero, ei libris vivendo duo, cum laboramus intellegat ex. Id vim legimus consequat.",
  author: "Nik",
  inCart: false,
  count: 0,
  total: 0
};