export const storeProducts = [
  {
    id: 1,
    title: "Rome Planter mini",
    img: "img/product-0.jpg",
    price: 4,
    size: "width: 2 inches; height: 2 inches",
    color: "wood-brown",
    material: "70% PLA, 30% composite wood fill. ecofriendly",
    info: "Give life to a new begining. Inspired by ancient Rome architecture, bring a piece of history into your modern home. This planter takes its roots from recycled wood, which is mixed with PLA plastic for strength and meltability. It feels and smells like wood too! I, myself, have many house plants and starting to enjoy my new collection of planters. I hope this product will make you and your plants happy and green!",
    author: "Nik",
    shipInfo: "in 1-2 business days",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 2,
    title: "Rome Planter small",
    img: "img/product-02.jpg",
    price: 6,
    size: "width: 3 inches; height: 3 inches",
    color: "wood-brown",
    material: "70% PLA, 30% composite, wood infill. ecofriendly",
    info: "Give life to a new begining. Inspired by ancient Rome architecture, bring a piece of history into your modern home. This planter takes its roots from recycled wood, which is mixed with PLA plastic for strength and meltability. It feels and smells like wood too! I, myself, have many house plants and starting to enjoy my new collection of planters. I hope this product will make you and your plants happy and green!",
    author: "Nik",
    shipInfo: "in 1-2 business days",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 3,
    title: "Rome Planter medium",
    img: "img/product-03.jpg",
    price: 8,
    size: "width: 4 inches; height: 4 inches",
    color: "wood-brown",
    material: "70% PLA, 30% composite, wood infill. ecofriendly",
    info: "Give life to a new begining. Inspired by ancient Rome architecture, bring a piece of history into your modern home. This planter takes its roots from recycled wood, which is mixed with PLA plastic for strength and meltability. It feels and smells like wood too! I, myself, have many house plants and starting to enjoy my new collection of planters. I hope this product will make you and your plants happy and green!",
    author: "Nik",
    shipInfo: "in 1-2 business days",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 4,
    title: "Rome Planter large",
    img: "img/product-04.jpg",
    price: 12,
    size: "width: 7 inches; height: 5 inches",
    color: "wood-brown",
    material: "70% PLA, 30% composite, wood infill. ecofriendly",
    info: "Give life to a new begining. Inspired by ancient Rome architecture, bring a piece of history into your modern home. This planter takes its roots from recycled wood, which is mixed with PLA plastic for strength and meltability. It feels and smells like wood too! I, myself, have many house plants and starting to enjoy my new collection of planters. I hope this product will make you and your plants happy and green!",
    author: "Nik",
    shipInfo: "in 1-2 business days",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "Planter",
    img: "img/product-5.png",
    price: 5,
    size: "Diameter 3 inches",
    color: "black",
    material: "",
    info: "Lorem ipsum dolor sit amet, mei iudico equidem an, duis decore persius sea ne. Duo nominati reformidans at. Ei mel soleat cetero, ei libris vivendo duo, cum laboramus intellegat ex. Id vim legimus consequat.",
    author: "Nik",
    shipInfo: "in 1-2 business days",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 6,
    title: "Table Wood Clock",
    img: "img/product-6.png",
    price: 40,
    size: "8 inches hexagon; 2 inches thickness",
    color: "brown",
    material: "wood",
    info: "Lorem ipsum dolor sit amet, mei iudico equidem an, duis decore persius sea ne. Duo nominati reformidans at. Ei mel soleat cetero, ei libris vivendo duo, cum laboramus intellegat ex. Id vim legimus consequat.",
    author: "Nik",
    shipInfo: "in 3-4 business days",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 7,
    title: "Paper Organizer",
    img: "img/product-7.png",
    price: 120,
    size: "height: 5 inches; width: 10.5 inches; depth: 15 inches; shelf depth: 9.25 inches; shelf depth: 12 inches",
    color: "light brown",
    material: "Reclaimed 100 yr old Douglas Fir, Oak dowels, acrylic tray, danish oil with walnut finish",
    info: "This is a one of a kind handmade paper organizer. The idea for this work originated from a need to keep things organized with style. Light walnut finished wood outlines the space for stored items, while the acrylic holder creates an illusion of empty space and lightness. The piece indeed is very light and sturdy. It can support several books, and at the same time perfect for notebooks or loose pieces of paper.",
    author: "Nik",
    shipInfo: "in 3-4 business days",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 8,
    title: "Winter Scarf",
    img: "img/product-8.png",
    price: 80,
    size: "",
    color: "dark blue",
    material: "",
    info: "Lorem ipsum dolor sit amet, mei iudico equidem an, duis decore persius sea ne. Duo nominati reformidans at. Ei mel soleat cetero, ei libris vivendo duo, cum laboramus intellegat ex. Id vim legimus consequat.",
    author: "Zinfira",
    shipInfo: "in 2-5 business days",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 9,
    title: "Blanket",
    img: "img/product-9.png",
    price: 150,
    size: "",
    color: "grey-pink",
    material: "",
    info: "Lorem ipsum dolor sit amet, mei iudico equidem an, duis decore persius sea ne. Duo nominati reformidans at. Ei mel soleat cetero, ei libris vivendo duo, cum laboramus intellegat ex. Id vim legimus consequat.",
    author: "Zinfira",
    shipInfo: "in 2-5 business days",
    inCart: false,
    count: 0,
    total: 0
  }
];

export const detailProduct = {
  id: 1,
  title: "Rome Planter mini",
  img: "img/product-1.png",
  price: 4,
  size: "width: 2 inches; height: 2 inches",
  color: "wood-brown",
  material: "70% PLA, 30% composite wood fill. ecofriendly",
  info: "Give life to a new begining. Inspired by ancient Rome architecture, bring a piece of history into your modern home. This planter takes its roots from recycled wood, which is mixed with PLA plastic for strength and meltability. It feels and smells like wood too! I, myself, have many house plants and starting to enjoy my new collection of planters. I hope this product will make you and your plants happy and green!",
  author: "Nik",
  shipInfo: "in 1-2 business days",
  inCart: false,
  count: 0,
  total: 0
};